import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Router, useRouter } from "next/router";
import Loader from "../../components/Loader";
import styles from "../../styles/shop.module.css";
import getStores from "../../snippets/getPlaces";

export async function getStaticProps() {
  const stores = await getStores();
  return {
    props: {
      stores,
    },
  };
}
// getStaticProps is serevr side function . it must be called asynchronously , in case you ar trying to render  some dynamic paths .

export async function getStaticPaths() {
  // mapping ove the response data array fro creating  array ofparams obj with key shopid to create static paths for those id's
  const stores = await getStores();
  const paths = stores.features?.map((obj) => {
    return { params: { shopid: obj.properties.place_id } };
  });

  return {
    paths,
    fallback: true,
  };
}

/*
this fallback value must be set to false in case there is not dynamic param in your paths array but may occuure in databse , so instead of showing 404 page 
    next will call getStaticProps for such route 
    else it will shown as 404 page 

*/

function CoffeeShop({ stores }) {
  const router = useRouter();
  const shopid = router.query.shopid;

  // fallback loader in case dynamic data is loading .
  if (router.isFallback) return <Loader />;

  const shop = stores.features.find((obj) => {
    if (obj.properties.place_id === shopid) return obj;
  });

  // in case path data related  path is not found
  if (!shop) return "this is not valid shop id ";

  const { imgUrl, name, street, formatted } = shop.properties;
  return (
    <>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className={styles.container}>
        <Link href="/">
          <a>Back to home</a>
        </Link>
        <section className={styles.section}>
          <Image src={shop.img} width={300} height={200} />
          <div className={styles.shopDetails}>
            <h1>{name}</h1>
            <h4>{formatted}</h4>
            <p> {street} </p>
            <p className={styles.likes}> 601 likes</p>
            <button onClick={upvote}> Upvote</button>
          </div>
        </section>
      </main>
    </>
  );
}

function upvote() {
  alert("upvote");
}

export default CoffeeShop;
