import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container";
import Card from "../components/Card";
import coffeeStores from "./data/data.json";
import getPlaces from "../snippets/getPlaces";
import getLocation from "../snippets/location.status";
import { useEffect, useState } from "react";

export default function Home({ stores }) {
  const { isLoading, getUserLocation, latlong, err } = getLocation();
  const [localStores, setLocalStores] = useState("");

  useEffect(async () => {
    if (latlong) {
      const localStores = await getPlaces("-87.770231,41.878968", "catering");
      setLocalStores(localStores);
    }
  }, [latlong]);

  async function getShops() {
    getUserLocation();
  }

  return (
    <div>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Container onclickHandler={getShops} isLoading={isLoading} />
      {err && <h2 className="locationError">{err}</h2>}
      {localStores && localStores.features.length ? (
        <Card stores={localStores} heading="Stores nearby " />
      ) : null}
      {localStores && !localStores.features.length ? (
        <h2 className="locationError">
          Seems like there is not place for coffee around you.{" "}
        </h2>
      ) : null}
      <Card stores={stores} heading="Famous coffee stores" />
    </div>
  );
}

export async function getStaticProps() {
  const stores = await getPlaces();
  return {
    props: {
      stores,
    },
  };
}